pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2 --net="bridge"'
        }
    }
    stages {
        stage('Unit Test') { 
            steps {
                configFileProvider([configFile(fileId: 'acaf626e-bcad-47c2-9ac8-66e73f40f3ce', variable: 'MAVEN_SETTINGS')]) {
                    sh 'mvn -s $MAVEN_SETTINGS clean test'
                }
            }
        }
        stage('Static Analysis') {
            steps {
                sh 'echo Hola mundo'
            }
        }
        stage('Build') {
            steps {
                configFileProvider([configFile(fileId: 'acaf626e-bcad-47c2-9ac8-66e73f40f3ce', variable: 'MAVEN_SETTINGS')]) {
                    sh 'mvn clean package -DskipTests=true deploy:deploy'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploy'
            }
        }
    }
}