pipeline {
    agent {
        docker {
            image 'maven:3.8.5-jdk-11'
            args '-v /root/.m2:/root/.m2 --net="tallerdeinvestigacin_devops"'
        }
    }
    stages {
        stage('Unit Test') { 
            steps {
                configFileProvider([configFile(fileId: 'acaf626e-bcad-47c2-9ac8-66e73f40f3ce', variable: 'MAVEN_SETTINGS')]) {
                    sh 'mvn -s $MAVEN_SETTINGS clean test'
                }
            }
        }
        stage('Static Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar_login', variable: 'SECRET')]) { //set SECRET with the credential content
                    sh 'mvn sonar:sonar -Dsonar.login=$SECRET -Dsonar.projectKey=Test1'
                }
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean install'
                configFileProvider([configFile(fileId: 'acaf626e-bcad-47c2-9ac8-66e73f40f3ce', variable: 'MAVEN_SETTINGS')]) {
                    sh 'mvn clean package -DskipTests=true -s $MAVEN_SETTINGS deploy:deploy'
                }
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo Deploy'
            }
        }
    }
}